repos:
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        args: ['--max-line-length=180', '-i']
        name: autopep8

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        name: flake8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: double-quote-string-fixer
    -   id: check-yaml
    -   id: pretty-format-json
        args: ['--autofix', '--indent', '4', '--no-ensure-ascii', '--no-sort-keys']
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
