# Generated by Django 4.2 on 2025-02-01 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloq',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=12)),
                ('isOccupied', models.BooleanField(default=False)),
                ('bloqId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bloq')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('waiting_dropoff', 'Waiting for Dropoff'), ('waiting_pickup', 'Waiting for Pickup'), ('delivered', 'Delivered')], max_length=18)),
                ('lockerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.locker')),
            ],
        ),
    ]
