# Generated by Django 4.2 on 2025-02-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bloq_locker_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=12),
        ),
        migrations.AlterField(
            model_name='rent',
            name='lockerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.locker'),
        ),
    ]
